import Head from 'next/head'
import Image from 'next/image'
import lecturestyles from '../styles/Lecture.module.css'
import MARQUEE from "react-fast-marquee";
import React, { useEffect, useRef, useLayoutEffect, useState } from "react";


if (typeof window !== "undefined") {
  window.onload = () => {
    
  }

  window.onclick = (e) => {
  }
}

const slideRef = React.createRef();
const SetHeight = () => {
  useEffect(() => {
    const slideHeight = slideRef && slideRef.current && slideRef.current.offsetHeight;
    console.log(slideHeight)
    window.parent.postMessage({ head: "changeHeight", body: {view: "Lecture", height: slideHeight } }, '*');
  }, []);
}

const getLectureSubjects = () => {
  const names = [
    {title: "4주차 강의 영상", src: "images/play-button.png"}, 
    {title: "4주차 2차시 00:00", src: "images/lecture.png"}, 
    {title: "4주차 강의 자료", src: "images/pdf.png"}
  ];
  const subjectList = names.map((subject, idx) => 
    <div key={"lectureSubject"+idx} className={lecturestyles.lecture_subject}>
      <img src={subject.src}/>
      <h3>{subject.title}</h3>
    </div>
  );

  return <div className={lecturestyles.lecture_subjects}>{subjectList}</div>;
}

const getLectureTodoLists = () => {
  const names = ["김익수교수님 사랑합니다", "수업시간 필기 정리하기", "수업시간 필기 정리하기", "수업시간 필기 정리하기", "수업시간 필기 정리하기"];
  const todoList = names.map((subject, idx) => 
    <div key={"lectureTodoList"+idx} className={lecturestyles.lecture_todolist_content}>
      <input className={lecturestyles.lecture_todolist_check} type="checkbox" name="check" id="GFG" value="1" defaultChecked />
      <div className={lecturestyles.lecture_todolist_title}>
        <h3>{subject}</h3>
        <hr/>
      </div>
    </div>
  );

  return <div className={lecturestyles.lecture_todolist}>{todoList}</div>;
}

const getLectureNotice = () => {
  return (
    <MARQUEE>안녕하세요 LMSSU입니다. 즐거운 학교생활 되세요~</MARQUEE>
  )
}

const getLectureItems = () => {
  const lectureSubjects = getLectureSubjects();
  const lectureTodoLists = getLectureTodoLists();

  const names = ["[오픈소스기반기초설계]", "[과목명]", "[과목명]"];
  const lectureNotice = getLectureNotice();

  const lectureList = names.map((lecture, idx) => 
    <div key={"lecture"+idx} className={lecturestyles.lecture_item}>
      <div className={lecturestyles.lecture_top_bar}>
        <h2>{lecture}</h2>
        <div className={lecturestyles.div_grow}></div>
        <img src="images/home-icon-silhouette.png"/>
      </div>
      <div className={lecturestyles.lecture_notice}>
        <img src="images/megaphone.png"/>
        <p>
          {lectureNotice}
        </p>
      </div>
      <div className={lecturestyles.lecture_content}>
        {lectureSubjects}
        {lectureTodoLists}
      </div>
    </div>
  );

  return <div className={lecturestyles.lecture_items}>{lectureList}</div>;
}


export default function Lecture() {

  const lectureItems = getLectureItems();

  return (
    <div ref={slideRef}>
      <Head>
        <title>LMSSU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={lecturestyles.lecture_board}>
          <div className={lecturestyles.lecture_week}>
            <h1>{"<"}</h1>
            <div>
              <h1>4주차</h1>
              <h5>10/15 ~ 10/22</h5>
            </div>
            <h1>{">"}</h1>
          </div>
          {lectureItems}
        </div>
      </main>
      
      <SetHeight/>
    </div>
  )
}
