import Head from 'next/head'
import Image from 'next/image'
import loginstyles from '../styles/Login.module.css'
import React, { useEffect, useRef, useLayoutEffect, useState, useCallback } from "react";
import axios from 'axios'

export default function Login() {

  const slideRef = React.createRef();

  const LoginForm = () => {
    const [values, setValues] = useState({
      stdid: "",
      pwd: "",
    })
  
    const [errors, setErrors] = useState({
      stdid: "",
      pwd: "",
    })
  
    // 필드 방문 상태를 관리한다
    const [touched, setTouched] = useState({
      stdid: false,
      pwd: false,
    })
  
    const handleChange = e => {
      setValues({
        ...values,
        [e.target.name]: e.target.value,
      })
    }
  
    // blur 이벤트가 발생하면 touched 상태를 true로 바꾼다
    const handleBlur = e => {
      setTouched({
        ...touched,
        [e.target.name]: true,
      })
    }
  
    const handleSubmit = async e => {
      let status = 0

      e.preventDefault()
  
      // 모든 필드에 방문했다고 표시한다.
      setTouched({
        stdid: true,
        pwd: true,
      })
  
      // 필드 검사 후 잘못된 값이면 제출 처리를 중단한다.
      const errors = validate()
      // 오류 메세지 상태를 갱신한다
      setErrors(errors)
      // 잘못된 값이면 제출 처리를 중단한다.
      if (Object.values(errors).some(v => v)) {
        return
      }
      
      await axios.post(process.env.FRONT_BASE_URL + "/api/crawl", {
        studentId: values.stdid,
        pwd: values.pwd
      }, {
        withCredentials: true
      }).then((response) => {
        console.log(response)
        if(response.data.status == 'FAIL') {
          alert("잘못된 학번 혹은 비밀번호입니다")
          return
        }
        status = 1
      }).catch((error) => {
        console.log(error.response)
        alert("ERROR!")
        return
      });

      if(status != 1) return

      await axios.post(process.env.FRONT_BASE_URL+"/apis/student/sign-in", {
        studentId: values.stdid,
        userId: values.stdid,
        pwd: values.pwd
      }, {
        withCredentials: true
      }).then((response) => {
        console.log(response)
        if(response.data.student == 'new') {
          status = 2
        }
      }).catch((error) => {
        console.log(error.response)
        alert("ERROR!")
        return
      });
      
      if(status == 1) {
        
      }
    }
  
    // 필드값을 검증한다.
    const validate = useCallback(() => {
      const errors = {
        stdid: "",
        pwd: "",
      }
  
      if (!values.stdid) {
        errors.stdid = "이메일을 입력하세요"
      }
      if (!values.pwd) {
        errors.pwd = "비밀번호를 입력하세요"
      }

      return errors
    }, [values])
  
    // 입력값이 변경될때 마다 검증한다.
    useEffect(() => {
      validate()
    }, [validate])
    
    return (
      <form onSubmit={handleSubmit} className={loginstyles.login_form}>
        <div>
          <h4>아이디</h4>
          <input
            type="text"
            name="stdid"
            placeholder="학번을 입력하세요"
            value={values.stdid}
            onChange={handleChange}
            onBlur={handleBlur}
          />
          {touched.stdid && errors.stdid && <h6>{errors.stdid}</h6>}
        </div>
        <div>
          <h4>비밀번호</h4>
          <input
            type="password"
            name="pwd"
            placeholder="비밀번호를 입력하세요"
            value={values.pwd}
            onChange={handleChange}
            onBlur={handleBlur}
          />
          {touched.pwd && errors.pwd && <h6>{errors.pwd}</h6>}
        </div>
        <button type="submit">로그인</button>
      </form>
    )
  }

  return (
    <div ref={slideRef}>
      <Head>
        <title>LMSSU 로그인</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={loginstyles.login_board}>
          <h2>LMSSU:로그인</h2>
          {LoginForm()}
        </div>
      </main>
    </div>
  )
}
