import Head from 'next/head'
import Image from 'next/image'
import noticestyles from '../styles/Notice.module.css'

if (typeof window !== "undefined") {
  window.onload = () => {
    document.querySelector('#notice_all').classList.add(noticestyles.notice_select);
    document.querySelector('#pageItem').classList.add(noticestyles.notice_page_select);
  }

  window.onclick = (e) => {
    if(e.target.classList.contains(noticestyles.notice_type)) {
      let selectedItem = document.getElementsByClassName(noticestyles.notice_type);
      for(let i = 0; i < selectedItem.length; i++) {
        if(selectedItem[i].classList.contains(noticestyles.notice_select)) {
          selectedItem[i].classList.remove(noticestyles.notice_select);
        }
      }
      e.target.classList.add(noticestyles.notice_select);
    }

    if(e.target.matches('#pageItem')) {
      let selectedItem = document.querySelectorAll('#pageItem');
      for(let i = 0; i < selectedItem.length; i++) {
        if(selectedItem[i].classList.contains(noticestyles.notice_page_select)) {
          selectedItem[i].classList.remove(noticestyles.notice_page_select);
        }
      }
      e.target.classList.add(noticestyles.notice_page_select);
    }
  }
}

const getNoticeList = () => {
  const names = ["Hello World", "Lorem Ipsum", "Opensource", "Hello", "World"];
  const nameList = names.map((name) => 
    <div>
      <div className={noticestyles.notice_content}>
        <p className={noticestyles.notice_content_dot}>·</p>
        <p className={noticestyles.notice_content_title}>
          {name}
        </p>
        <div></div>
        <p className={noticestyles.notice_content_date}>2022.10.04</p>
      </div>
      <hr />
    </div>
  );

  return <div className={noticestyles.notice_contents}>{nameList}</div>;
}

export default function Notice() {
  const noticeList = getNoticeList();

  return (
    <div>
      <Head>
        <title>LMSSU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={noticestyles.notice_board}>
          <div className={noticestyles.notice_type_title}>
            <div id="notice_all" className={noticestyles.notice_type}>
              <h4>전체</h4>
              <div className={noticestyles.notice_bot_bar}></div>
            </div>
            <div id="notice_major" className={noticestyles.notice_type}>
              <h4>학과</h4>
              <div className={noticestyles.notice_bot_bar}></div>
            </div>
            <div id="notice_fun" className={noticestyles.notice_type}>
              <h4>펀시스템</h4>
              <div className={noticestyles.notice_bot_bar}></div>
            </div>
            <div id="notice_etc" className={noticestyles.notice_type}>
              <h4>기타</h4>
              <div className={noticestyles.notice_bot_bar}></div>
            </div>
          </div>
          <div className={noticestyles.notice_contents}>
            {noticeList}
          </div>
          <div className={noticestyles.notice_page}>
            <div className={noticestyles.div_grow}></div>
            <h4>{"<"}</h4>
              <div className={noticestyles.notice_page_number}>
                <h4 id="pageItem">1</h4>
                <h4 id="pageItem">2</h4>
                <h4 id="pageItem">3</h4>
                <h4 id="pageItem">4</h4>
                <h4 id="pageItem">5</h4>
              </div>
            <h4>{">"}</h4>
            <div class="div_grow"></div>
          </div>
        </div>
      </main>
    </div>
  )
}
