import Head from 'next/head'
import Image from 'next/image'
import noticestyles from '../styles/Notice.module.css'
import React, { useEffect, useRef, useLayoutEffect, useState } from "react";

if (typeof window !== "undefined") {
  window.onload = () => {
  }

  window.onclick = (e) => {
    if(e.target.classList.contains(noticestyles.notice_type)) {
      let selectedItem = document.getElementsByClassName(noticestyles.notice_type);
      for(let i = 0; i < selectedItem.length; i++) {
        if(selectedItem[i].classList.contains(noticestyles.notice_select)) {
          selectedItem[i].classList.remove(noticestyles.notice_select);
        }
      }
      e.target.classList.add(noticestyles.notice_select);
    }

    if(e.target.matches('#pageItems > h4')) {
      let selectedItem = document.querySelectorAll('#pageItems > h4');
      for(let i = 0; i < selectedItem.length; i++) {
        if(selectedItem[i].classList.contains(noticestyles.notice_page_select)) {
          selectedItem[i].classList.remove(noticestyles.notice_page_select);
        }
      }
      e.target.classList.add(noticestyles.notice_page_select);
    }
  }
}

const slideRef = React.createRef();
const SetHeight = () => {
  useEffect(() => {
    document.querySelector('#notice_all').classList.add(noticestyles.notice_select);
    document.querySelector('#pageItems > h4').classList.add(noticestyles.notice_page_select);
    
    const slideHeight = slideRef && slideRef.current && slideRef.current.offsetHeight;
    console.log(slideHeight)
    window.parent.postMessage({ head: "changeHeight", body: {view: "Notice", height: slideHeight } }, '*');
  }, []);
}

const getNoticeList = () => {
  const names = ["Hello World", "Lorem Ipsum", "Opensource", "Hello", "World"];
  const nameList = names.map((name, idx) => 
    <div key={"notice"+idx}>
      <div className={noticestyles.notice_content}>
        <p className={noticestyles.notice_content_dot}>·</p>
        <p className={noticestyles.notice_content_title}>
          {name}
        </p>
        <div></div>
        <p className={noticestyles.notice_content_date}>2022.10.04</p>
      </div>
      <hr />
    </div>
  );

  return <div className={noticestyles.notice_contents}>{nameList}</div>;
}

const getNoticePage = () => {
  let num = 1;
  let min = num - 2;
  let max = num + 2;
  if(min <= 0) {
    max = max - min + 1;
    min = min - min + 1;
  }

  const arr = [];
  for(let i = min; i <= max; i++) {
    arr[i-min] = i;
  }

  const pageList = arr.map((page, idx) => 
    <h4 key={"page"+idx} id={"page"+page}>{page}</h4>
  );

  return (
    <div id="pageItems" className={noticestyles.notice_page_number}>
      {pageList}
    </div>
  )
}

export default function Notice() {
  const noticeList = getNoticeList();
  const noticePage = getNoticePage();

  return (
    <div ref={slideRef}>
      <Head>
        <title>LMSSU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={noticestyles.notice_board}>
          <div className={noticestyles.notice_type_title}>
            <div id="notice_all" className={noticestyles.notice_type}>
              <h4>전체</h4>
              <div className={noticestyles.notice_bot_bar}></div>
            </div>
            <div id="notice_major" className={noticestyles.notice_type}>
              <h4>학과</h4>
              <div className={noticestyles.notice_bot_bar}></div>
            </div>
            <div id="notice_fun" className={noticestyles.notice_type}>
              <h4>펀시스템</h4>
              <div className={noticestyles.notice_bot_bar}></div>
            </div>
            <div id="notice_etc" className={noticestyles.notice_type}>
              <h4>기타</h4>
              <div className={noticestyles.notice_bot_bar}></div>
            </div>
          </div>
          <div className={noticestyles.notice_contents}>
            {noticeList}
          </div>
          <div className={noticestyles.notice_page}>
            <div className={noticestyles.div_grow}></div>
            <h4>{"<"}</h4>
            {noticePage}
            <h4>{">"}</h4>
            <div className={noticestyles.div_grow}></div>
          </div>
        </div>
      </main>
      
      <SetHeight/>
    </div>
  )
}
