import Head from 'next/head'
import Image from 'next/image'
import subjectstyles from '../styles/Subject.module.css'
import React, { useEffect, useRef, useLayoutEffect, useState } from "react";

if (typeof window !== "undefined") {
  window.onload = () => {

  }

  window.onclick = (e) => {

  }
}

const slideRef = React.createRef();
const SetHeight = () => {
  useEffect(() => {
    const slideHeight = slideRef && slideRef.current && slideRef.current.offsetHeight;
    console.log(slideHeight)
    window.parent.postMessage({ head: "changeHeight", body: {view: "Subject", height: slideHeight } }, '*');
  }, []);
}

const getSubjectList = () => {
  const names = ["데이터베이스", "오픈소스기반기초설계", "운영체제", "웹프로그래밍설계", "컴퓨터비전"];
  const subjectList = names.map((subject, idx) => 
    <div key={"subject"+idx}>
      <hr/>
      <div className={subjectstyles.subject_item}>
        <h5>{subject}</h5>
        <div className={subjectstyles.div_grow}></div>
        <h5 className={subjectstyles.subject_fold}>∨</h5>
      </div>
    </div>
  );

  return (
    <div className={subjectstyles.subject_list}>
      {subjectList}
      <h3>더보기 +</h3>
    </div>
  )
}

export default function Subject() {
  const subjectList = getSubjectList();

  return (
    <div ref={slideRef}>
      <Head>
        <title>LMSSU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={subjectstyles.subject_board}>
          <h2>미완료 수업</h2>
          {subjectList}
        </div>
      </main>
      
      <SetHeight/>
    </div>
  )
}
