import Head from 'next/head'
import Image from 'next/image'
import subjectstyles from '../styles/Subject.module.css'
import React, { useRef, useLayoutEffect, useState } from "react";

if (typeof window !== "undefined") {
  window.onload = () => {

  }

  window.onclick = (e) => {

  }
}

const getSubjectList = () => {
  const names = ["Hello World1", "Hello World2", "Hello World3", "Hello World4", "Hello World5"];
  const subjectList = names.map((subject) => 
    <div>
      <hr/>
      <div className={subjectstyles.subject_item}>
        <h5>{subject}</h5>
        <div className={subjectstyles.div_grow}></div>
        <h5 className={subjectstyles.subject_fold}>∨</h5>
      </div>
    </div>
  );

  return (
    <div className={subjectstyles.subject_list}>
      {subjectList}
      <h3>더보기 +</h3>
    </div>
  )
}

export default function Notice() {
  const subjectList = getSubjectList();

  return (
    <div>
      <Head>
        <title>LMSSU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={subjectstyles.subject_board}>
          <h2>미완료 수업</h2>
          {subjectList}
        </div>
      </main>
    </div>
  )
}
